### ISSUE TITLE
Wrong Day Of Week

### ISSUE THREAD

**Issue by amarbibek** [subeshb1/Nepali-Date#29] opened 2020-08-24 08:59 UTC
It is giving the wrong day of the week .

let a = new NepaliDate(2077,05,08);

a.format('ddd DD, MMMM YYYY', 'np')
// "बिहिबार ०८, आश्विन २०७७" <-- output

// "सोमबार ०८, भाद्र २०७७" <-- Actual Date in Nepali

**Comment by subeshb1** [comment] 2020-08-27 08:45
Hi @amarbibek,
Sorry for the late reply. 

The constructor is as follows:
```
NepaliDate(year: number, monthIndex: number, date: number)
```
You are passing in date for the month of Ashwin whose month index is 5.  So, it is showing the date of next month. For Bhadra, the index is 4. The month index is expected in this constructor. This is done to make it consistent with the existing javascript Date library which uses the same approach.

Reference from the doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

Here are the constructor docs:
https://subeshb1.github.io/Nepali-Date/classes/nepalidate.html

**Comment by subeshb1** [comment] 2020-08-27 08:46
Closing this as a duplicate of https://github.com/subeshb1/Nepali-Date/issues/25

Feel free to re-open ore create another issue if your queries are not met.

**Closed by subeshb1** 2020-08-27 08:46 UTC
Labels: duplicate, not-a-bug

**Comment by amarbibek** [comment] 2020-08-27 13:06
Thanks for the response.

I could figure that out. 
My actual concern is the day of the week, "०८, आश्विन २०७७" was "सोमबार " not "बिहिबार".

**Comment by subeshb1** [comment] 2020-08-27 14:40
For Bhadra:
<img width="297" alt="Screen Shot 2020-08-27 at 20 19 10" src="https://user-images.githubusercontent.com/27361350/91456081-93c92380-e8a2-11ea-8058-273f7ac1df78.png">

For Ashwin:
<img width="360" alt="Screen Shot 2020-08-27 at 20 24 09" src="https://user-images.githubusercontent.com/27361350/91456677-4600eb00-e8a3-11ea-9ec9-a3b307f5ec1b.png">

The weekday is Thursday for `Ashwin 8, 2077`:
<img width="666" alt="Screen Shot 2020-08-27 at 20 23 05" src="https://user-images.githubusercontent.com/27361350/91456773-62048c80-e8a3-11ea-9f16-adc05a4dfc8e.png">


Is it not right? Do let me know. Thanks!

**Comment by amarbibek** [comment] 2020-08-27 14:58
I see.
It got messed up because of month.
Thank you very much.
